# Generated by Django 5.1.3 on 2024-12-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0003_rename_final_balace_transaction_final_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('SAVING', 'SAVING'), ('CURRENT', 'CURRENT')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('WITHDRAW', 'WITHDRAW'), ('TRANSFER_IN', 'TRANSFER_IN'), ('TRANSFER_OUT', 'TRANSFER_OUT')], max_length=20),
        ),
    ]
