# Generated by Django 5.1.3 on 2024-12-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0004_alter_account_type_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pin',
            field=models.CharField(default='1111', max_length=4),
        ),
    ]
