# Generated by Django 5.1.3 on 2024-12-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0005_account_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.CharField(max_length=4),
        ),
    ]
